service: nestjs-gh-actions-lambda

# Use useDotenv: true to load environment variables from a .env file when running serverless offline
# useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SECRETORPRIVATEKEY: ${env:SECRETORPRIVATEKEY}
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_DATABASE: ${env:DATABASE_DATABASE}
    PROJECT_ENVIRONMENT: ${env:PROJECT_ENVIRONMENT}
    NODE_ENV: production

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
    package:
      individually: true
      include:
        - src/schema.gpl
      patterns:
        - 'dist/**'
        - 'src/schema.gpl'
